In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
import os

In [3]:
os.getcwd()

'/Users/vijvalrallan'

In [4]:
os.chdir('/Users/vijvalrallan/Downloads')

In [5]:
os.getcwd()

'/Users/vijvalrallan/Downloads'

In [6]:
df = pd.read_csv('/Users/vijvalrallan/Downloads/hacktrain.csv')

In [7]:
df

Unnamed: 0     ID       class  20150720_N  20150602_N  20150517_N  \
0              0      1       water    637.5950     658.668   -1882.030   
1              1      2       water    634.2400     593.705   -1625.790   
2              3      4       water     58.0174   -1599.160         NaN   
3              4      5       water     72.5180         NaN     380.436   
4              7      8       water   1136.4400         NaN         NaN   
...          ...    ...         ...         ...         ...         ...   
7995       10537  10538  impervious   1207.7000     984.620         NaN   
7996       10538  10539  impervious   2170.3500    1419.720    1361.000   
7997       10541  10542  impervious   1895.6800    1454.740         NaN   
7998       10542  10543  impervious   3465.7400    1283.320     413.412   
7999       10544  10545  impervious   6941.1900    1667.870    5084.780   

      20150501_N  20150415_N  20150330_N  20150314_N  ...  20140610_N  \
0       -1924.36     997.904   -1739.990     630.087  ...         NaN   
1       -1672.32     914.198    -692.386     707.626  ...         NaN   
2       -1052.63         NaN   -1564.630         NaN  ...   -1025.880   
3       -1256.93     515.805   -1413.180    -802.942  ...   -1813.950   
4        1647.83    1935.800         NaN    2158.980  ...    1535.000   
...          ...         ...         ...         ...  ...         ...   
7995     1166.25     937.478    1072.700     823.896  ...    1117.740   
7996     1478.71     983.911    1262.110    1422.860  ...     984.634   
7997     1033.56    1930.380    1057.150    1471.600  ...     888.408   
7998     4391.05    1146.820    4473.050    1614.750  ...    5833.760   
7999         NaN    1588.950    5978.190         NaN  ...    7352.570   

      20140525_N  20140509_N  20140423_N  20140407_N  20140322_N  20140218_N  \
0      -1043.160   -1942.490     267.138         NaN         NaN     211.328   
1       -933.934    -625.385     120.059     364.858     476.972     220.878   
2        368.622         NaN   -1227.800     304.621         NaN     369.214   
3        155.624         NaN    -924.073     432.150     282.833     298.320   
4       1959.430    -279.317    -384.915    -113.406    1020.720    1660.650   
...          ...         ...         ...         ...         ...         ...   
7995    1176.600    1044.110         NaN     369.082     465.843     362.882   
7996    2128.970    1379.660         NaN     762.633     485.204     446.724   
7997    2093.020    1232.110    1190.830    1441.460    1170.880    1095.000   
7998    4047.320    4515.800     433.177     277.296     744.143         NaN   
7999    3289.860    3729.150    1994.980         NaN    5299.900         NaN   

      20140202_N  20140117_N  20140101_N  
0      -2203.020    -1180.19     433.906  
1      -2250.000    -1360.56     524.075  
2      -2202.120         NaN   -1343.550  
3      -2197.360         NaN    -826.727  
4       -116.801     -568.05   -1357.140  
...          ...         ...         ...  
7995     979.795         NaN     433.659  
7996     771.747     1589.06     506.936  
7997    1818.650     2501.72    1247.770  
7998    3759.710         NaN     388.346  
7999    5983.130     1249.71    2424.230  

[8000 rows x 30 columns]

In [8]:
df.shape

(8000, 30)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  8000 non-null   int64  
 1   ID          8000 non-null   int64  
 2   class       8000 non-null   object 
 3   20150720_N  7440 non-null   float64
 4   20150602_N  6800 non-null   float64
 5   20150517_N  7200 non-null   float64
 6   20150501_N  7040 non-null   float64
 7   20150415_N  7520 non-null   float64
 8   20150330_N  6880 non-null   float64
 9   20150314_N  7280 non-null   float64
 10  20150226_N  6640 non-null   float64
 11  20150210_N  7360 non-null   float64
 12  20150125_N  6960 non-null   float64
 13  20150109_N  7120 non-null   float64
 14  20141117_N  6720 non-null   float64
 15  20141101_N  7600 non-null   float64
 16  20141016_N  6560 non-null   float64
 17  20140930_N  7200 non-null   float64
 18  20140813_N  7440 non-null   float64
 19  20140626_N  6400 non-null  

In [10]:
df.describe(include = 'all')

Unnamed: 0            ID   class   20150720_N   20150602_N  \
count    8000.000000   8000.000000    8000  7440.000000  6800.000000   
unique           NaN           NaN       6          NaN          NaN   
top              NaN           NaN  forest          NaN          NaN   
freq             NaN           NaN    6159          NaN          NaN   
mean     4984.202625   4985.202625     NaN  5845.476916  4868.091395   
std      2900.022898   2900.022898     NaN  2261.409128  2758.499942   
min         0.000000      1.000000     NaN  -433.735000 -1781.790000   
25%      2514.750000   2515.750000     NaN  4331.232500  2067.265000   
50%      4917.500000   4918.500000     NaN  6908.255000  5513.375000   
75%      7311.250000   7312.250000     NaN  7626.845000  7555.570000   
max     10544.000000  10545.000000     NaN  8376.150000  8566.420000   

         20150517_N   20150501_N   20150415_N   20150330_N   20150314_N  ...  \
count   7200.000000  7040.000000  7520.000000  6880.000000  7280.000000  ...   
unique          NaN          NaN          NaN          NaN          NaN  ...   
top             NaN          NaN          NaN          NaN          NaN  ...   
freq            NaN          NaN          NaN          NaN          NaN  ...   
mean    4469.837748  5193.485086  2927.586705  4924.493648  3313.881373  ...   
std     2876.218394  2510.389832  2728.325670  2600.418802  2434.828743  ...   
min    -2939.740000 -1924.360000 -1794.870000 -1848.910000 -1574.970000  ...   
25%     1521.195000  3087.072500   500.515750  2398.385000   992.778250  ...   
50%     4672.000000  5810.755000  1586.240000  5742.485000  2802.010000  ...   
75%     7431.697500  7511.880000  5703.067500  7280.110000  5508.350000  ...   
max     8650.500000  8516.100000  8267.120000  8499.330000  8001.700000  ...   

         20140610_N   20140525_N   20140509_N   20140423_N   20140407_N  \
count   7520.000000  7280.000000  7120.000000  6240.000000  7360.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean    4872.681670  3674.886731  3012.178524  3055.167358  2041.316792   
std     2776.135418  2331.105635  2068.334108  2209.985887  2040.354512   
min    -2683.600000 -1043.160000 -2435.900000 -1505.780000 -1445.370000   
25%     2010.732500  1369.355000  1368.742500  1009.827500   419.987000   
50%     5484.905000  3659.770000  2633.695000  2624.125000  1183.715000   
75%     7607.755000  5927.035000  4128.082500  4952.317500  3075.997500   
max     8489.970000  7981.820000  8445.410000  7762.980000  8078.080000   

         20140322_N   20140218_N   20140202_N   20140117_N   20140101_N  
count   6880.000000  6560.000000  7440.000000  6800.000000  7600.000000  
unique          NaN          NaN          NaN          NaN          NaN  
top             NaN          NaN          NaN          NaN          NaN  
freq            NaN          NaN          NaN          NaN          NaN  
mean    2799.820342  2144.360224  6259.064275  2629.203972  2578.449870  
std     2452.563243  2267.606759  1825.563702  2386.147667  2436.270797  
min       55.564100  -232.292000 -2729.430000 -2139.860000 -4145.250000  
25%      791.741250   501.602750  5938.257500   691.171500   689.199000  
50%     1599.385000   969.711500  6941.010000  1521.210000  1439.950000  
75%     4909.997500  3227.380000  7395.612500  4452.257500  4146.342500  
max     8216.700000  8247.630000  8410.330000  8418.230000  8502.020000  

[11 rows x 30 columns]

In [11]:
df.columns

Index(['Unnamed: 0', 'ID', 'class', '20150720_N', '20150602_N', '20150517_N',
       '20150501_N', '20150415_N', '20150330_N', '20150314_N', '20150226_N',
       '20150210_N', '20150125_N', '20150109_N', '20141117_N', '20141101_N',
       '20141016_N', '20140930_N', '20140813_N', '20140626_N', '20140610_N',
       '20140525_N', '20140509_N', '20140423_N', '20140407_N', '20140322_N',
       '20140218_N', '20140202_N', '20140117_N', '20140101_N'],
      dtype='object')

In [12]:
df.isnull().sum()

Unnamed: 0       0
ID               0
class            0
20150720_N     560
20150602_N    1200
20150517_N     800
20150501_N     960
20150415_N     480
20150330_N    1120
20150314_N     720
20150226_N    1360
20150210_N     640
20150125_N    1040
20150109_N     880
20141117_N    1280
20141101_N     400
20141016_N    1440
20140930_N     800
20140813_N     560
20140626_N    1600
20140610_N     480
20140525_N     720
20140509_N     880
20140423_N    1760
20140407_N     640
20140322_N    1120
20140218_N    1440
20140202_N     560
20140117_N    1200
20140101_N     400
dtype: int64

In [13]:
df.drop(columns = ['ID', 'Unnamed: 0'], inplace = True)

In [14]:
df.head()

class  20150720_N  20150602_N  20150517_N  20150501_N  20150415_N  \
0  water    637.5950     658.668   -1882.030    -1924.36     997.904   
1  water    634.2400     593.705   -1625.790    -1672.32     914.198   
2  water     58.0174   -1599.160         NaN    -1052.63         NaN   
3  water     72.5180         NaN     380.436    -1256.93     515.805   
4  water   1136.4400         NaN         NaN     1647.83    1935.800   

   20150330_N  20150314_N  20150226_N  20150210_N  ...  20140610_N  \
0   -1739.990     630.087         NaN    -1325.64  ...         NaN   
1    -692.386     707.626   -1670.590    -1408.64  ...         NaN   
2   -1564.630         NaN     729.790    -3162.14  ...    -1025.88   
3   -1413.180    -802.942     683.254    -2829.40  ...    -1813.95   
4         NaN    2158.980         NaN     1242.87  ...     1535.00   

   20140525_N  20140509_N  20140423_N  20140407_N  20140322_N  20140218_N  \
0   -1043.160   -1942.490     267.138         NaN         NaN     211.328   
1    -933.934    -625.385     120.059     364.858     476.972     220.878   
2     368.622         NaN   -1227.800     304.621         NaN     369.214   
3     155.624         NaN    -924.073     432.150     282.833     298.320   
4    1959.430    -279.317    -384.915    -113.406    1020.720    1660.650   

   20140202_N  20140117_N  20140101_N  
0   -2203.020    -1180.19     433.906  
1   -2250.000    -1360.56     524.075  
2   -2202.120         NaN   -1343.550  
3   -2197.360         NaN    -826.727  
4    -116.801     -568.05   -1357.140  

[5 rows x 28 columns]

In [15]:
X = df.drop(columns = ['class'])
y = df['class']

In [16]:
X

20150720_N  20150602_N  20150517_N  20150501_N  20150415_N  20150330_N  \
0       637.5950     658.668   -1882.030    -1924.36     997.904   -1739.990   
1       634.2400     593.705   -1625.790    -1672.32     914.198    -692.386   
2        58.0174   -1599.160         NaN    -1052.63         NaN   -1564.630   
3        72.5180         NaN     380.436    -1256.93     515.805   -1413.180   
4      1136.4400         NaN         NaN     1647.83    1935.800         NaN   
...          ...         ...         ...         ...         ...         ...   
7995   1207.7000     984.620         NaN     1166.25     937.478    1072.700   
7996   2170.3500    1419.720    1361.000     1478.71     983.911    1262.110   
7997   1895.6800    1454.740         NaN     1033.56    1930.380    1057.150   
7998   3465.7400    1283.320     413.412     4391.05    1146.820    4473.050   
7999   6941.1900    1667.870    5084.780         NaN    1588.950    5978.190   

      20150314_N  20150226_N  20150210_N  20150125_N  ...  20140610_N  \
0        630.087         NaN   -1325.640    -944.084  ...         NaN   
1        707.626   -1670.590   -1408.640    -989.285  ...         NaN   
2            NaN     729.790   -3162.140         NaN  ...   -1025.880   
3       -802.942     683.254   -2829.400   -1267.540  ...   -1813.950   
4       2158.980         NaN    1242.870   -2646.050  ...    1535.000   
...          ...         ...         ...         ...  ...         ...   
7995     823.896     943.698     944.619    1040.990  ...    1117.740   
7996    1422.860    1401.970    1372.680    1142.340  ...     984.634   
7997    1471.600         NaN    2693.630    2377.550  ...     888.408   
7998    1614.750     770.469         NaN    2676.000  ...    5833.760   
7999         NaN    3068.030    6471.470    7150.420  ...    7352.570   

      20140525_N  20140509_N  20140423_N  20140407_N  20140322_N  20140218_N  \
0      -1043.160   -1942.490     267.138         NaN         NaN     211.328   
1       -933.934    -625.385     120.059     364.858     476.972     220.878   
2        368.622         NaN   -1227.800     304.621         NaN     369.214   
3        155.624         NaN    -924.073     432.150     282.833     298.320   
4       1959.430    -279.317    -384.915    -113.406    1020.720    1660.650   
...          ...         ...         ...         ...         ...         ...   
7995    1176.600    1044.110         NaN     369.082     465.843     362.882   
7996    2128.970    1379.660         NaN     762.633     485.204     446.724   
7997    2093.020    1232.110    1190.830    1441.460    1170.880    1095.000   
7998    4047.320    4515.800     433.177     277.296     744.143         NaN   
7999    3289.860    3729.150    1994.980         NaN    5299.900         NaN   

      20140202_N  20140117_N  20140101_N  
0      -2203.020    -1180.19     433.906  
1      -2250.000    -1360.56     524.075  
2      -2202.120         NaN   -1343.550  
3      -2197.360         NaN    -826.727  
4       -116.801     -568.05   -1357.140  
...          ...         ...         ...  
7995     979.795         NaN     433.659  
7996     771.747     1589.06     506.936  
7997    1818.650     2501.72    1247.770  
7998    3759.710         NaN     388.346  
7999    5983.130     1249.71    2424.230  

[8000 rows x 27 columns]

In [17]:
X_cleaned = X.copy()

In [18]:
# Impute missing values: median if outliers exist, mean otherwise
for col in X.columns:
    series = X_cleaned[col]
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    has_outliers = ((series < lower_bound) | (series > upper_bound)).any()

    if has_outliers:
        impute_value = series.median()
    else:
        impute_value = series.mean()

    X_cleaned[col].fillna(impute_value, inplace=True)

# Confirm all missing values are handled
missing_after_imputation = X_cleaned[X.columns].isnull().sum().sum()
missing_after_imputation

0

In [19]:
X_cleaned.describe()

20150720_N   20150602_N   20150517_N   20150501_N   20150415_N  \
count  8000.000000  8000.000000  8000.000000  8000.000000  8000.000000   
mean   5845.476916  4868.091395  4469.837748  5193.485086  2927.586705   
std    2180.813726  2543.183231  2728.601401  2354.934333  2645.199325   
min    -433.735000 -1781.790000 -2939.740000 -1924.360000 -1794.870000   
25%    4710.735000  2698.627500  1742.820000  3505.257500   532.103250   
50%    6714.640000  4868.091395  4469.837748  5193.485086  1902.285000   
75%    7593.770000  7331.677500  7212.610000  7364.137500  5457.340000   
max    8376.150000  8566.420000  8650.500000  8516.100000  8267.120000   

        20150330_N   20150314_N   20150226_N   20150210_N   20150125_N  ...  \
count  8000.000000  8000.000000  8000.000000  8000.000000  8000.000000  ...   
mean   4924.493648  3313.881373  4987.520158  4320.961814  5237.037739  ...   
std    2411.504651  2322.664227  2436.976334  2692.845816  2576.654936  ...   
min   -1848.910000 -1574.970000 -2532.490000 -3403.050000 -2849.860000  ...   
25%    3080.940000  1091.465000  3196.902500  1531.300000  3376.475000  ...   
50%    4924.493648  3313.881373  4987.520158  4320.961814  5798.460000  ...   
75%    7101.790000  5268.065000  7243.962500  7108.257500  7493.610000  ...   
max    8499.330000  8001.700000  8452.380000  8422.060000  8401.100000  ...   

       20140610_N   20140525_N   20140509_N   20140423_N   20140407_N  \
count  8000.00000  8000.000000  8000.000000  8000.000000  8000.000000   
mean   4872.68167  3674.886731  2970.545336  3055.167358  1972.708649   
std    2691.55241  2223.719300  1954.838203  1951.772275  1970.811846   
min   -2683.60000 -1043.160000 -2435.900000 -1505.780000 -1445.370000   
25%    2160.11750  1542.455000  1544.167500  1272.827500   446.283000   
50%    5052.97500  3674.886731  2633.695000  3055.167358  1183.715000   
75%    7559.10500  5720.952500  3902.450000  4274.220000  2837.752500   
max    8489.97000  7981.820000  8445.410000  7762.980000  8078.080000   

        20140322_N   20140218_N   20140202_N   20140117_N   20140101_N  
count  8000.000000  8000.000000  8000.000000  8000.000000  8000.000000  
mean   2799.820342  1932.923453  6306.800476  2629.203972  2578.449870  
std    2274.390441  2102.389430  1769.080101  2199.895183  2374.575231  
min      55.564100  -232.292000 -2729.430000 -2139.860000 -4145.250000  
25%     889.501250   575.229250  6073.270000   781.651750   712.964750  
50%    2263.200000   969.711500  6941.010000  2220.670000  1596.530000  
75%    4067.285000  2311.732500  7365.035000  3752.205000  3907.092500  
max    8216.700000  8247.630000  8410.330000  8418.230000  8502.020000  

[8 rows x 27 columns]

In [20]:
# Check class distribution
class_distribution = df['class'].value_counts()
class_distribution_percentage = df['class'].value_counts(normalize=True) * 100

# Combine and display
class_distribution_df = pd.DataFrame({
    'Count': class_distribution,
    'Percentage': class_distribution_percentage.round(2)
})
print(class_distribution_df)

            Count  Percentage
forest       6159       76.99
farm          841       10.51
impervious    669        8.36
grass         196        2.45
water         105        1.31
orchard        30        0.38


In [21]:
from sklearn.preprocessing import RobustScaler

# Columns to scale (NDVI features)
ndvi_columns = X_cleaned.columns  # assuming first 3 columns are ID, Unnamed, class

# Initialize and apply RobustScaler
scaler = RobustScaler()
X_cleaned[ndvi_columns] = scaler.fit_transform(X_cleaned[ndvi_columns])

# Optional: View summary of scaled features
print(X_cleaned[ndvi_columns].describe())

         20150720_N    20150602_N    20150517_N   20150501_N   20150415_N  \
count  8.000000e+03  8.000000e+03  8.000000e+03  8000.000000  8000.000000   
mean  -3.014750e-01 -7.105427e-17  2.486900e-17     0.000000     0.208173   
std    7.564298e-01  5.489220e-01  4.988494e-01     0.610264     0.537070   
min   -2.479462e+00 -1.435314e+00 -1.354637e+00    -1.844537    -0.750655   
25%   -6.950679e-01 -4.682583e-01 -4.985599e-01    -0.437492    -0.278196   
50%    1.577379e-16  0.000000e+00  0.000000e+00     0.000000     0.000000   
75%    3.049321e-01  5.317417e-01  5.014401e-01     0.562508     0.721804   
max    5.763059e-01  7.982492e-01  7.643186e-01     0.861031     1.292290   

         20150330_N    20150314_N    20150226_N    20150210_N    20150125_N  \
count  8.000000e+03  8.000000e+03  8.000000e+03  8.000000e+03  8.000000e+03   
mean  -2.131628e-17 -6.394885e-17 -1.136868e-16 -7.105427e-17 -1.363624e-01   
std    5.997500e-01  5.561136e-01  6.021597e-01  4.828521e-01  6.2583

In [22]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
# Step 1: Encode target class
le = LabelEncoder()
y = le.fit_transform(y)

# Step 2: Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_cleaned, y, test_size=0.2, stratify=y, random_state=42
)

In [23]:
corr = X_train.corr().abs()
upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
X_train_reduced = X_train.drop(columns=to_drop)
X_test_reduced = X_test.drop(columns=to_drop)

In [24]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
# Keep interaction_only=True to avoid unnecessary explosion
poly = PolynomialFeatures(degree=3, interaction_only=True, include_bias=False)
X_train_poly = poly.fit_transform(X_train_reduced)
X_test_poly = poly.transform(X_test_reduced)

# Fit your best logistic model here
model = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    C=100,
    class_weight='balanced',
    max_iter=1000
)
model.fit(X_train_poly, y_train)
y_pred = model.predict(X_test_poly)
print("Classification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

        farm       0.83      0.86      0.84       168
      forest       0.98      0.96      0.97      1232
       grass       0.74      0.74      0.74        39
  impervious       0.75      0.89      0.82       134
     orchard       0.67      0.67      0.67         6
       water       0.71      0.57      0.63        21

    accuracy                           0.94      1600
   macro avg       0.78      0.78      0.78      1600
weighted avg       0.94      0.94      0.94      1600

Confusion Matrix:
 [[ 144   10    0   13    0    1]
 [  18 1188    8   13    2    3]
 [   1    4   29    5    0    0]
 [   8    4    2  119    0    1]
 [   1    1    0    0    4    0]
 [   1    0    0    8    0   12]]


In [25]:
df2 = pd.read_csv('hacktest.csv')

In [26]:
df2

Unnamed: 0    ID  20150720_N  20150602_N  20150517_N  20150501_N  \
0              0     1   7466.4200     413.162    5761.000     5625.45   
1              1     2   7235.2600    6037.350    1027.560     6085.14   
2              2     3   7425.0800    6969.980    1177.940     7408.93   
3              3     4   7119.1200    1731.620    6311.930     6441.61   
4              4     5   7519.5500    8130.260    1482.540     7879.53   
...          ...   ...         ...         ...         ...         ...   
2840        2840  2841  -1673.7400   -2514.480   -2451.190    -2738.44   
2841        2841  2842    -96.8233    -412.727   -1795.400    -2363.82   
2842        2842  2843  -2364.6000    -155.592   -1422.090    -1713.40   
2843        2843  2844  -3004.6300   -1217.120     180.122    -1113.89   
2844        2844  2845  -2975.1000   -1129.790     463.748    -5355.40   

      20150415_N  20150330_N  20150314_N  20150226_N  ...  20140610_N  \
0       489.4030     3923.84    3097.110  6766.42000  ...     801.184   
1      1618.0500     6668.54    2513.990  1051.69000  ...    5533.470   
2       861.0610     7644.43     814.458  1504.29000  ...    1981.390   
3       465.9790     7128.42    1649.120  6935.22000  ...     959.344   
4      1001.2100     7937.60    4122.530  1094.51000  ...    7636.070   
...          ...         ...         ...         ...  ...         ...   
2840     64.4464    -2275.03   -2881.100 -4738.97000  ...   -2257.890   
2841  -2168.1900    -2162.68   -3155.740 -4416.11000  ...   -3991.910   
2842    465.6220    -2230.40   -3088.730 -5010.32000  ...   -2484.500   
2843    438.4180    -2442.51   -3210.560 -3237.74000  ...   -3291.490   
2844    193.5110    -2590.16   -3113.520    -2.38883  ...   -3058.230   

      20140525_N  20140509_N  20140423_N  20140407_N  20140322_N  20140218_N  \
0        927.115     4704.14     6378.42     340.949   2695.5700     527.268   
1       5103.040     5216.12     4885.27    4366.790   1234.1400    3298.110   
2       6204.540     7021.69     5704.41    4897.450   1789.9900    2206.100   
3       5794.150     1045.57     5572.90     586.287    685.9060    1287.000   
4       6996.760     7413.43     4596.13    4511.700   1413.5200    3283.940   
...          ...         ...         ...         ...         ...         ...   
2840   -2582.420    -1699.10    -2295.30     306.483    209.4030     221.920   
2841   -2614.910    -2109.84    -2687.18   -2853.890     71.3402     -86.414   
2842   -1756.080    -3820.43    -1988.23     433.852    291.8000     254.548   
2843   -2018.450    -3472.65    -3109.07     511.792    369.0970     276.948   
2844   -2276.180    -3335.00    -2929.19   -1007.500    271.0580     307.997   

      20140202_N  20140117_N  20140101_N  
0        4736.75     601.843    6639.760  
1        6942.68    1070.440     842.101  
2        6928.93    1036.560     831.441  
3        6734.72     824.584    6883.610  
4        7937.68    1857.800    1336.920  
...          ...         ...         ...  
2840    -4885.15   -2630.590     356.233  
2841    -5109.01     324.637   -4316.580  
2842    -4259.30     412.115   -1170.750  
2843    -5574.51     298.739     460.419  
2844    -5453.33     307.495     417.124  

[2845 rows x 29 columns]

In [27]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845 entries, 0 to 2844
Data columns (total 29 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  2845 non-null   int64  
 1   ID          2845 non-null   int64  
 2   20150720_N  2845 non-null   float64
 3   20150602_N  2845 non-null   float64
 4   20150517_N  2845 non-null   float64
 5   20150501_N  2845 non-null   float64
 6   20150415_N  2845 non-null   float64
 7   20150330_N  2845 non-null   float64
 8   20150314_N  2845 non-null   float64
 9   20150226_N  2845 non-null   float64
 10  20150210_N  2845 non-null   float64
 11  20150125_N  2845 non-null   float64
 12  20150109_N  2845 non-null   float64
 13  20141117_N  2845 non-null   float64
 14  20141101_N  2845 non-null   float64
 15  20141016_N  2845 non-null   float64
 16  20140930_N  2845 non-null   float64
 17  20140813_N  2845 non-null   float64
 18  20140626_N  2845 non-null   float64
 19  20140610_N  2845 non-null  

In [28]:
df2.describe()

Unnamed: 0           ID   20150720_N   20150602_N   20150517_N  \
count  2845.000000  2845.000000  2845.000000  2845.000000  2845.000000   
mean   1422.000000  1423.000000  5285.311732  4524.020744  3970.782482   
std     821.425083   821.425083  2375.641035  2683.209632  2835.736587   
min       0.000000     1.000000 -3363.640000 -3345.120000 -5774.370000   
25%     711.000000   712.000000  3277.960000  2080.930000  1251.970000   
50%    1422.000000  1423.000000  6089.850000  4776.980000  3755.380000   
75%    2133.000000  2134.000000  7370.970000  7107.910000  6704.870000   
max    2844.000000  2845.000000  8377.720000  8533.770000  8527.390000   

        20150501_N   20150415_N   20150330_N   20150314_N   20150226_N  ...  \
count  2845.000000  2845.000000  2845.000000  2845.000000  2845.000000  ...   
mean   4619.879362  2650.444746  4707.699198  3399.498607  4547.764233  ...   
std    2545.021404  2498.047435  2617.748386  2455.988128  2828.650853  ...   
min   -5355.400000 -3232.180000 -5992.080000 -3520.840000 -5604.450000  ...   
25%    2629.150000   584.177000  2353.060000  1070.800000  1971.150000  ...   
50%    4763.230000  1556.290000  5295.060000  3202.980000  5117.820000  ...   
75%    6949.620000  4550.290000  7114.520000  5557.170000  7217.340000  ...   
max    8501.490000  8211.380000  8416.930000  7954.460000  8439.350000  ...   

        20140610_N   20140525_N   20140509_N   20140423_N   20140407_N  \
count  2845.000000  2845.000000  2845.000000  2845.000000  2845.000000   
mean   4372.211461  3507.372651  3029.266553  2944.609166  2004.551484   
std    2685.492110  2211.572661  2053.854976  2132.625853  1935.035216   
min   -3991.910000 -3257.730000 -4869.010000 -4212.560000 -2853.890000   
25%    1812.710000  1495.400000  1482.540000  1052.600000   460.419000   
50%    4571.050000  3391.960000  2778.340000  2727.780000  1398.370000   
75%    6988.020000  5411.160000  4380.210000  4571.120000  2765.040000   
max    8480.190000  7797.990000  8430.740000  7919.070000  8206.780000   

        20140322_N   20140218_N   20140202_N   20140117_N   20140101_N  
count  2845.000000  2845.000000  2845.000000  2845.000000  2845.000000  
mean   2348.475869  1786.190268  5562.937183  2388.282039  2529.853365  
std    2218.498698  2003.596912  2414.344589  2234.440944  2418.944853  
min   -4354.630000  -106.117000 -6807.550000 -4550.190000 -4723.980000  
25%     702.187000   478.272000  4460.340000   678.423000   654.996000  
50%    1340.560000   857.606000  6523.100000  1427.090000  1554.730000  
75%    3510.240000  2160.030000  7289.490000  3800.560000  4195.840000  
max    8235.400000  8197.020000  8388.040000  8363.950000  8261.640000  

[8 rows x 29 columns]

In [29]:
X2 = df2.drop(columns = ['Unnamed: 0', 'ID'])

In [30]:
X2

20150720_N  20150602_N  20150517_N  20150501_N  20150415_N  20150330_N  \
0      7466.4200     413.162    5761.000     5625.45    489.4030     3923.84   
1      7235.2600    6037.350    1027.560     6085.14   1618.0500     6668.54   
2      7425.0800    6969.980    1177.940     7408.93    861.0610     7644.43   
3      7119.1200    1731.620    6311.930     6441.61    465.9790     7128.42   
4      7519.5500    8130.260    1482.540     7879.53   1001.2100     7937.60   
...          ...         ...         ...         ...         ...         ...   
2840  -1673.7400   -2514.480   -2451.190    -2738.44     64.4464    -2275.03   
2841    -96.8233    -412.727   -1795.400    -2363.82  -2168.1900    -2162.68   
2842  -2364.6000    -155.592   -1422.090    -1713.40    465.6220    -2230.40   
2843  -3004.6300   -1217.120     180.122    -1113.89    438.4180    -2442.51   
2844  -2975.1000   -1129.790     463.748    -5355.40    193.5110    -2590.16   

      20150314_N  20150226_N  20150210_N  20150125_N  ...  20140610_N  \
0       3097.110  6766.42000    2829.130    6742.570  ...     801.184   
1       2513.990  1051.69000    7268.220    6908.180  ...    5533.470   
2        814.458  1504.29000    7002.630    6086.560  ...    1981.390   
3       1649.120  6935.22000    2176.800     690.408  ...     959.344   
4       4122.530  1094.51000    7951.440    8001.350  ...    7636.070   
...          ...         ...         ...         ...  ...         ...   
2840   -2881.100 -4738.97000   -4293.570   -4402.210  ...   -2257.890   
2841   -3155.740 -4416.11000   -5648.660   -5193.280  ...   -3991.910   
2842   -3088.730 -5010.32000   -4211.420   -3354.430  ...   -2484.500   
2843   -3210.560 -3237.74000    -192.857   -2857.540  ...   -3291.490   
2844   -3113.520    -2.38883   -1248.450     328.306  ...   -3058.230   

      20140525_N  20140509_N  20140423_N  20140407_N  20140322_N  20140218_N  \
0        927.115     4704.14     6378.42     340.949   2695.5700     527.268   
1       5103.040     5216.12     4885.27    4366.790   1234.1400    3298.110   
2       6204.540     7021.69     5704.41    4897.450   1789.9900    2206.100   
3       5794.150     1045.57     5572.90     586.287    685.9060    1287.000   
4       6996.760     7413.43     4596.13    4511.700   1413.5200    3283.940   
...          ...         ...         ...         ...         ...         ...   
2840   -2582.420    -1699.10    -2295.30     306.483    209.4030     221.920   
2841   -2614.910    -2109.84    -2687.18   -2853.890     71.3402     -86.414   
2842   -1756.080    -3820.43    -1988.23     433.852    291.8000     254.548   
2843   -2018.450    -3472.65    -3109.07     511.792    369.0970     276.948   
2844   -2276.180    -3335.00    -2929.19   -1007.500    271.0580     307.997   

      20140202_N  20140117_N  20140101_N  
0        4736.75     601.843    6639.760  
1        6942.68    1070.440     842.101  
2        6928.93    1036.560     831.441  
3        6734.72     824.584    6883.610  
4        7937.68    1857.800    1336.920  
...          ...         ...         ...  
2840    -4885.15   -2630.590     356.233  
2841    -5109.01     324.637   -4316.580  
2842    -4259.30     412.115   -1170.750  
2843    -5574.51     298.739     460.419  
2844    -5453.33     307.495     417.124  

[2845 rows x 27 columns]

In [31]:
X2_cleaned = X2.copy()

In [32]:
ndvi_columns = X2_cleaned.columns  
X2_cleaned[ndvi_columns] = scaler.transform(X2_cleaned[ndvi_columns])

In [33]:
X2_poly = poly.transform(X2_cleaned)

In [34]:
y_final = model.predict(X2_poly)

In [35]:
y_final

array([0, 4, 4, ..., 3, 3, 1])

In [36]:
y_decoded = le.inverse_transform(y_final)

In [37]:
y_decoded

array(['farm', 'orchard', 'orchard', ..., 'impervious', 'impervious',
       'forest'], dtype=object)

In [38]:
result = pd.DataFrame({
    'ID': df2['ID'],
    'class': y_decoded
})

In [39]:
result

ID       class
0        1        farm
1        2     orchard
2        3     orchard
3        4     orchard
4        5     orchard
...    ...         ...
2840  2841  impervious
2841  2842       water
2842  2843  impervious
2843  2844  impervious
2844  2845      forest

[2845 rows x 2 columns]

In [40]:
result.to_csv('submission.csv', index = False)