In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
os.getcwd()

'/Users/vijvalrallan'

In [3]:
os.chdir('/Users/vijvalrallan/Downloads')

In [4]:
df = pd.read_csv('Train_Data.csv')

In [5]:
df

SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  \
0     73564.0       2.0     2.0    35.7   110.0     2.0   150.0  14.91   
1     73568.0       2.0     2.0    20.3    89.0     2.0    80.0   3.85   
2     73576.0       1.0     2.0    23.2    89.0     2.0    68.0   6.14   
3     73577.0       1.0     2.0    28.9   104.0     NaN    84.0  16.15   
4     73580.0       2.0     1.0    35.9   103.0     2.0    81.0  10.92   
...       ...       ...     ...     ...     ...     ...     ...    ...   
1961  83711.0       2.0     2.0    33.5   100.0     2.0    73.0   6.53   
1962  83712.0       1.0     2.0    30.0    93.0     2.0   208.0  13.02   
1963  83713.0       1.0     2.0    23.7   103.0     2.0   124.0  21.41   
1964  83718.0       2.0     2.0    27.4    90.0     2.0   108.0   4.99   
1965  83727.0       1.0     2.0    24.5     NaN     2.0   108.0   3.76   

     age_group  
0        Adult  
1        Adult  
2        Adult  
3        Adult  
4        Adult  
...        ...  
1961     Adult  
1962     Adult  
1963     Adult  
1964     Adult  
1965     Adult  

[1966 rows x 9 columns]

In [6]:
df.head()

SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN age_group
0  73564.0       2.0     2.0    35.7   110.0     2.0   150.0  14.91     Adult
1  73568.0       2.0     2.0    20.3    89.0     2.0    80.0   3.85     Adult
2  73576.0       1.0     2.0    23.2    89.0     2.0    68.0   6.14     Adult
3  73577.0       1.0     2.0    28.9   104.0     NaN    84.0  16.15     Adult
4  73580.0       2.0     1.0    35.9   103.0     2.0    81.0  10.92     Adult

In [7]:
df.nunique()

SEQN         1954
RIAGENDR        2
PAQ605          3
BMXBMI        332
LBXGLU         95
DIQ010          3
LBXGLT        224
LBXIN        1292
age_group       2
dtype: int64

In [8]:
df.shape

(1966, 9)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1966 entries, 0 to 1965
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   SEQN       1954 non-null   float64
 1   RIAGENDR   1948 non-null   float64
 2   PAQ605     1953 non-null   float64
 3   BMXBMI     1948 non-null   float64
 4   LBXGLU     1953 non-null   float64
 5   DIQ010     1948 non-null   float64
 6   LBXGLT     1955 non-null   float64
 7   LBXIN      1957 non-null   float64
 8   age_group  1952 non-null   object 
dtypes: float64(8), object(1)
memory usage: 138.4+ KB


In [10]:
df.describe(include = 'all')

SEQN     RIAGENDR       PAQ605       BMXBMI       LBXGLU  \
count    1954.000000  1948.000000  1953.000000  1948.000000  1953.000000   
unique           NaN          NaN          NaN          NaN          NaN   
top              NaN          NaN          NaN          NaN          NaN   
freq             NaN          NaN          NaN          NaN          NaN   
mean    78683.621801     1.510267     1.825397    27.965400    99.491039   
std      2924.115709     0.500023     0.399449     7.327616    16.774665   
min     73564.000000     1.000000     1.000000    14.500000    63.000000   
25%     76194.000000     1.000000     2.000000    22.800000    91.000000   
50%     78717.000000     2.000000     2.000000    26.800000    97.000000   
75%     81217.000000     2.000000     2.000000    31.300000   104.000000   
max     83727.000000     2.000000     7.000000    70.100000   405.000000   

             DIQ010       LBXGLT        LBXIN age_group  
count   1948.000000  1955.000000  1957.000000      1952  
unique          NaN          NaN          NaN         2  
top             NaN          NaN          NaN     Adult  
freq            NaN          NaN          NaN      1638  
mean       2.015914   115.150384    11.862892       NaN  
std        0.187579    46.271615     9.756713       NaN  
min        1.000000    40.000000     0.140000       NaN  
25%        2.000000    87.000000     5.800000       NaN  
50%        2.000000   105.000000     9.030000       NaN  
75%        2.000000   131.000000    14.480000       NaN  
max        3.000000   604.000000   102.290000       NaN

In [11]:
df[df['age_group'] == 'Adult']

SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  \
0     73564.0       2.0     2.0    35.7   110.0     2.0   150.0  14.91   
1     73568.0       2.0     2.0    20.3    89.0     2.0    80.0   3.85   
2     73576.0       1.0     2.0    23.2    89.0     2.0    68.0   6.14   
3     73577.0       1.0     2.0    28.9   104.0     NaN    84.0  16.15   
4     73580.0       2.0     1.0    35.9   103.0     2.0    81.0  10.92   
...       ...       ...     ...     ...     ...     ...     ...    ...   
1961  83711.0       2.0     2.0    33.5   100.0     2.0    73.0   6.53   
1962  83712.0       1.0     2.0    30.0    93.0     2.0   208.0  13.02   
1963  83713.0       1.0     2.0    23.7   103.0     2.0   124.0  21.41   
1964  83718.0       2.0     2.0    27.4    90.0     2.0   108.0   4.99   
1965  83727.0       1.0     2.0    24.5     NaN     2.0   108.0   3.76   

     age_group  
0        Adult  
1        Adult  
2        Adult  
3        Adult  
4        Adult  
...        ...  
1961     Adult  
1962     Adult  
1963     Adult  
1964     Adult  
1965     Adult  

[1638 rows x 9 columns]

In [12]:
df[df['age_group'] == 'Senior']

SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  \
8     73607.0       1.0     2.0    38.9    89.0     2.0   113.0  17.47   
12    73621.0       1.0     2.0    24.6   100.0     2.0    97.0   4.33   
14    73639.0       1.0     2.0    30.3   133.0     2.0   295.0  22.92   
15    73640.0       2.0     1.0    22.1   114.0     2.0   150.0  10.09   
25    73690.0       2.0     2.0    21.4    90.0     2.0    76.0   3.47   
...       ...       ...     ...     ...     ...     ...     ...    ...   
1941  83615.0       1.0     2.0    24.9   105.0     2.0   100.0   9.50   
1946  83630.0       2.0     2.0    26.0   106.0     2.0   166.0  13.32   
1949  83638.0       1.0     2.0    24.2   116.0     2.0   157.0  13.81   
1957  83692.0       NaN     2.0    19.1    89.0     2.0   136.0   1.56   
1959  83702.0       2.0     2.0    27.9   111.0     2.0    72.0  13.91   

     age_group  
8       Senior  
12      Senior  
14      Senior  
15      Senior  
25      Senior  
...        ...  
1941    Senior  
1946    Senior  
1949    Senior  
1957    Senior  
1959    Senior  

[314 rows x 9 columns]

In [13]:
df.isnull().sum()

SEQN         12
RIAGENDR     18
PAQ605       13
BMXBMI       18
LBXGLU       13
DIQ010       18
LBXGLT       11
LBXIN         9
age_group    14
dtype: int64

In [14]:
#sequence number identifier only can be dropped holds no predictive value
df.drop(['SEQN'],axis = 1, inplace = True)

In [15]:
df

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN age_group
0          2.0     2.0    35.7   110.0     2.0   150.0  14.91     Adult
1          2.0     2.0    20.3    89.0     2.0    80.0   3.85     Adult
2          1.0     2.0    23.2    89.0     2.0    68.0   6.14     Adult
3          1.0     2.0    28.9   104.0     NaN    84.0  16.15     Adult
4          2.0     1.0    35.9   103.0     2.0    81.0  10.92     Adult
...        ...     ...     ...     ...     ...     ...    ...       ...
1961       2.0     2.0    33.5   100.0     2.0    73.0   6.53     Adult
1962       1.0     2.0    30.0    93.0     2.0   208.0  13.02     Adult
1963       1.0     2.0    23.7   103.0     2.0   124.0  21.41     Adult
1964       2.0     2.0    27.4    90.0     2.0   108.0   4.99     Adult
1965       1.0     2.0    24.5     NaN     2.0   108.0   3.76     Adult

[1966 rows x 8 columns]

In [16]:
df['RIAGENDR'].fillna(df['RIAGENDR'].mode()[0], inplace = True)

In [17]:
df['PAQ605'].fillna(df['PAQ605'].mode()[0], inplace = True)

In [18]:
df['BMXBMI'].fillna(df['BMXBMI'].median(), inplace = True)

In [19]:
df['LBXGLU'].fillna(df['LBXGLU'].median(), inplace = True)

In [20]:
df['DIQ010'].value_counts()

2.0    1879
3.0      50
1.0      19
Name: DIQ010, dtype: int64

In [21]:
df['DIQ010'].fillna(df['DIQ010'].mode()[0], inplace = True)

In [22]:
df['LBXGLT'].fillna(df['LBXGLT'].median(), inplace = True)

In [23]:
df['LBXIN'].fillna(df['LBXIN'].median(), inplace = True)

In [24]:
df['age_group'].value_counts()

Adult     1638
Senior     314
Name: age_group, dtype: int64

In [25]:
df['age_group'].fillna(df['age_group'].mode()[0], inplace = True)

In [26]:
df['age_group'].value_counts()

Adult     1652
Senior     314
Name: age_group, dtype: int64

In [27]:
df['age_group'] = df['age_group'].map({'Adult' : 0, 'Senior' : 1})

In [28]:
df['age_group'].value_counts()

0    1652
1     314
Name: age_group, dtype: int64

In [29]:
df0 = df[df['age_group'] == 0]
df1 = df[df['age_group'] == 1]

In [30]:
x = df.drop('age_group', axis = 1)
y = df['age_group']

In [31]:
x = pd.get_dummies(x, columns=['RIAGENDR'], drop_first=True)
x

PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  RIAGENDR_2.0
0        2.0    35.7   110.0     2.0   150.0  14.91             1
1        2.0    20.3    89.0     2.0    80.0   3.85             1
2        2.0    23.2    89.0     2.0    68.0   6.14             0
3        2.0    28.9   104.0     2.0    84.0  16.15             0
4        1.0    35.9   103.0     2.0    81.0  10.92             1
...      ...     ...     ...     ...     ...    ...           ...
1961     2.0    33.5   100.0     2.0    73.0   6.53             1
1962     2.0    30.0    93.0     2.0   208.0  13.02             0
1963     2.0    23.7   103.0     2.0   124.0  21.41             0
1964     2.0    27.4    90.0     2.0   108.0   4.99             1
1965     2.0    24.5    97.0     2.0   108.0   3.76             0

[1966 rows x 7 columns]

In [32]:
def count_outliers_iqr(df):
    outlier_counts = {}
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            Q1 = df[col].quantile(0.25)
            Q3 = df[col].quantile(0.75)
            IQR = Q3 - Q1
            lower = Q1 - 1.5 * IQR
            upper = Q3 + 1.5 * IQR
            outliers = df[(df[col] < lower) | (df[col] > upper)]
            outlier_counts[col] = outliers.shape[0]
    return pd.DataFrame(list(outlier_counts.items()), columns=["Feature", "Outlier Count"])

count_outliers_iqr(x)

Feature  Outlier Count
0        PAQ605            347
1        BMXBMI             76
2        LBXGLU             90
3        DIQ010             69
4        LBXGLT            105
5         LBXIN            130
6  RIAGENDR_2.0              0

In [33]:
def cap_outliers_specific(df, columns):
    df_capped = df.copy()
    for col in columns:
        if pd.api.types.is_numeric_dtype(df_capped[col]):
            lower = df_capped[col].quantile(0.01)
            upper = df_capped[col].quantile(0.99)
            df_capped[col] = df_capped[col].clip(lower, upper)
    return df_capped

In [34]:
columns_to_cap = ['BMXBMI', 'LBXGLU', 'LBXGLT','LBXIN']
x = cap_outliers_specific(x, columns_to_cap)

In [35]:
x

PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  RIAGENDR_2.0
0        2.0    35.7   110.0     2.0   150.0  14.91             1
1        2.0    20.3    89.0     2.0    80.0   3.85             1
2        2.0    23.2    89.0     2.0    68.0   6.14             0
3        2.0    28.9   104.0     2.0    84.0  16.15             0
4        1.0    35.9   103.0     2.0    81.0  10.92             1
...      ...     ...     ...     ...     ...    ...           ...
1961     2.0    33.5   100.0     2.0    73.0   6.53             1
1962     2.0    30.0    93.0     2.0   208.0  13.02             0
1963     2.0    23.7   103.0     2.0   124.0  21.41             0
1964     2.0    27.4    90.0     2.0   108.0   4.99             1
1965     2.0    24.5    97.0     2.0   108.0   3.76             0

[1966 rows x 7 columns]

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

In [37]:
from sklearn.preprocessing import RobustScaler
nhanes_columns = ['BMXBMI','LBXGLU','LBXGLT','LBXIN']
scaler = RobustScaler()
x_train[nhanes_columns] = scaler.fit_transform(x_train[nhanes_columns])

In [38]:
x_test[nhanes_columns] = scaler.transform(x_test[nhanes_columns])

In [39]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [40]:
def model_evaluation(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    print('For training dataset: ')
    y_pred = model.predict(x_train)
    print('-' * 65)
    print(confusion_matrix(y_pred,y_train))
    print('-' * 65)
    print(classification_report(y_pred,y_train))
    print('-' * 65)
    print('f1-score:',f1_score(y_pred,y_train))
    print('-' * 65)
    print('For testing dataset: ')
    y_pred_test = model.predict(x_test)
    print('-' * 65)
    print(confusion_matrix(y_pred_test,y_test))
    print('-' * 65)
    print(classification_report(y_pred_test,y_test))
    print('-' * 65)
    print('f1-score:', f1_score(y_pred_test,y_test))

In [41]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(class_weight = 'balanced', max_iter = 1000)
model_evaluation(lr,x_train,x_test,y_train,y_test)

For training dataset: 
-----------------------------------------------------------------
[[970  77]
 [337 188]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.74      0.93      0.82      1047
           1       0.71      0.36      0.48       525

    accuracy                           0.74      1572
   macro avg       0.73      0.64      0.65      1572
weighted avg       0.73      0.74      0.71      1572

-----------------------------------------------------------------
f1-score: 0.4759493670886076
-----------------------------------------------------------------
For testing dataset: 
-----------------------------------------------------------------
[[233  24]
 [112  25]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.68      0.91      0.77       257
           1       0.51      0.18      0.27     

In [42]:
from sklearn.svm import SVC
support_vector = SVC()
model_evaluation(support_vector,x_train,x_test,y_train,y_test)

For training dataset: 
-----------------------------------------------------------------
[[1296  237]
 [  11   28]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.99      0.85      0.91      1533
           1       0.11      0.72      0.18        39

    accuracy                           0.84      1572
   macro avg       0.55      0.78      0.55      1572
weighted avg       0.97      0.84      0.89      1572

-----------------------------------------------------------------
f1-score: 0.18421052631578946
-----------------------------------------------------------------
For testing dataset: 
-----------------------------------------------------------------
[[338  45]
 [  7   4]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.98      0.88      0.93       383
           1       0.08      0.36      0.13

In [43]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(class_weight = 'balanced')
model_evaluation(dtc,x_train,x_test,y_train,y_test)

For training dataset: 
-----------------------------------------------------------------
[[1307    0]
 [   0  265]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1307
           1       1.00      1.00      1.00       265

    accuracy                           1.00      1572
   macro avg       1.00      1.00      1.00      1572
weighted avg       1.00      1.00      1.00      1572

-----------------------------------------------------------------
f1-score: 1.0
-----------------------------------------------------------------
For testing dataset: 
-----------------------------------------------------------------
[[298  36]
 [ 47  13]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.86      0.89      0.88       334
           1       0.27      0.22      0.24        60

    

In [44]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(class_weight = 'balanced', max_depth = 15)
model_evaluation(rfc,x_train,x_test,y_train,y_test)

For training dataset: 
-----------------------------------------------------------------
[[1305    0]
 [   2  265]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1305
           1       1.00      0.99      1.00       267

    accuracy                           1.00      1572
   macro avg       1.00      1.00      1.00      1572
weighted avg       1.00      1.00      1.00      1572

-----------------------------------------------------------------
f1-score: 0.9962406015037594
-----------------------------------------------------------------
For testing dataset: 
-----------------------------------------------------------------
[[331  41]
 [ 14   8]]
-----------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.96      0.89      0.92       372
           1       0.16      0.36      0.23 

In [45]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
x_train_sm, y_train_sm = smote.fit_resample(x_train, y_train)

In [46]:
lr.fit(x_train_sm,y_train_sm)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [47]:
y_pred = lr.predict(x_test)

print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.68      0.78       345
           1       0.18      0.49      0.26        49

    accuracy                           0.66       394
   macro avg       0.54      0.59      0.52       394
weighted avg       0.81      0.66      0.71       394

F1 Score: 0.26229508196721313


In [48]:
param_grid = {
    'C': [0.01, 0.1, 1, 10],  
    'penalty': ['l2'],
    'solver': ['liblinear'],
    'class_weight': ['balanced']
}

In [49]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(LogisticRegression(), param_grid, scoring='f1', cv=5)
grid.fit(x_train_sm,y_train_sm)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10], 'class_weight': ['balanced'],
                         'penalty': ['l2'], 'solver': ['liblinear']},
             scoring='f1')

In [50]:
print("Best Params:", grid.best_params_)
print("Best F1 Score (CV):", grid.best_score_)

Best Params: {'C': 1, 'class_weight': 'balanced', 'penalty': 'l2', 'solver': 'liblinear'}
Best F1 Score (CV): 0.7198197378107057


In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score
final_model = LogisticRegression(
    C=1,
    class_weight='balanced',
    penalty='l2',
    solver='liblinear',
    max_iter=1000
)

final_model.fit(x_train_sm, y_train_sm)

# Predict on original test data
y_pred = final_model.predict(x_test)

# Evaluate
print(classification_report(y_test, y_pred, target_names=["Adult", "Senior"]))
print("Test F1 Score (class 1):", f1_score(y_test, y_pred))

              precision    recall  f1-score   support

       Adult       0.90      0.68      0.78       345
      Senior       0.18      0.49      0.26        49

    accuracy                           0.66       394
   macro avg       0.54      0.59      0.52       394
weighted avg       0.81      0.66      0.71       394

Test F1 Score (class 1): 0.26229508196721313


In [52]:
y_probs = final_model.predict_proba(x_test)[:, 1]  # probabilities for class 1 (Senior)

In [53]:
threshold = 0.5
y_pred_custom = (y_probs >= threshold).astype(int)

In [54]:
print(f"Results at threshold = {threshold}")
print(classification_report(y_test, y_pred_custom, target_names=["Adult", "Senior"]))
print("F1 Score (class 1):", f1_score(y_test, y_pred_custom))

Results at threshold = 0.5
              precision    recall  f1-score   support

       Adult       0.90      0.68      0.78       345
      Senior       0.18      0.49      0.26        49

    accuracy                           0.66       394
   macro avg       0.54      0.59      0.52       394
weighted avg       0.81      0.66      0.71       394

F1 Score (class 1): 0.26229508196721313


In [55]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(final_model, x, y)
print(scores)
print(scores.mean())

[0.71827411 0.74045802 0.70229008 0.70737913 0.70483461]
0.7146471887472391


In [56]:
scores = cross_val_score(support_vector, x, y)
print(scores)
print(scores.mean())

[0.84010152 0.84223919 0.83969466 0.83969466 0.83969466]
0.840284935611785


In [57]:
scores = cross_val_score(dtc, x, y)
print(scores)
print(scores.mean())

[0.79187817 0.75063613 0.76335878 0.77608142 0.7735369 ]
0.771098280828199


In [58]:
scores = cross_val_score(rfc, x, y)
print(scores)
print(scores.mean())

[0.84771574 0.84732824 0.83715013 0.82188295 0.8346056 ]
0.8377365314320404


In [59]:
df_test = pd.read_csv('Test_Data.csv')

In [60]:
df_test

SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN
0    77017.0       1.0     1.0    32.2    96.0     2.0   135.0  15.11
1    75580.0       2.0     2.0    26.3   100.0     2.0   141.0  15.26
2    73820.0       1.0     2.0    28.6   107.0     2.0   136.0   8.82
3    80489.0       2.0     1.0    22.1    93.0     2.0   111.0  12.13
4    82047.0       1.0     1.0    24.7    91.0     2.0   105.0   3.12
..       ...       ...     ...     ...     ...     ...     ...    ...
307  74150.0       2.0     2.0    21.9    82.0     2.0    82.0   2.54
308  82550.0       2.0     1.0    33.3    95.0     2.0    77.0   6.36
309  77835.0       2.0     2.0    41.5    91.0     2.0   149.0  15.52
310  79281.0       2.0     2.0    22.5    82.0     2.0    93.0   1.39
311  77214.0       1.0     2.0    16.1    96.0     2.0   197.0   8.57

[312 rows x 8 columns]

In [61]:
df_test.isna().sum()

SEQN        2
RIAGENDR    2
PAQ605      1
BMXBMI      1
LBXGLU      1
DIQ010      1
LBXGLT      2
LBXIN       1
dtype: int64

In [62]:
df_test.drop('SEQN', axis = 1, inplace = True)

In [63]:
df_test.shape

(312, 7)

In [64]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   RIAGENDR  310 non-null    float64
 1   PAQ605    311 non-null    float64
 2   BMXBMI    311 non-null    float64
 3   LBXGLU    311 non-null    float64
 4   DIQ010    311 non-null    float64
 5   LBXGLT    310 non-null    float64
 6   LBXIN     311 non-null    float64
dtypes: float64(7)
memory usage: 17.2 KB


In [65]:
df_test.describe(include = 'all')

RIAGENDR      PAQ605      BMXBMI      LBXGLU      DIQ010      LBXGLT  \
count  310.000000  311.000000  311.000000  311.000000  311.000000  310.000000   
mean     1.522581    1.803859   27.810611  100.067524    2.019293  114.241935   
std      0.500297    0.397717    6.717031   23.920539    0.159477   52.356101   
min      1.000000    1.000000   15.900000   69.000000    1.000000   43.000000   
25%      1.000000    2.000000   22.950000   92.000000    2.000000   86.000000   
50%      2.000000    2.000000   26.800000   97.000000    2.000000  102.500000   
75%      2.000000    2.000000   30.900000  103.000000    2.000000  128.750000   
max      2.000000    2.000000   54.900000  368.000000    3.000000  510.000000   

            LBXIN  
count  311.000000  
mean    11.666463  
std      9.570438  
min      1.040000  
25%      6.120000  
50%      9.220000  
75%     14.185000  
max     81.790000

In [66]:
df_test['RIAGENDR'].fillna(df_test['RIAGENDR'].mode()[0], inplace = True)
df_test['PAQ605'].fillna(df_test['PAQ605'].mode()[0], inplace = True)
df_test['BMXBMI'].fillna(df_test['BMXBMI'].median(), inplace = True)
df_test['LBXGLU'].fillna(df_test['LBXGLU'].median(), inplace = True)
df_test['DIQ010'].fillna(df_test['DIQ010'].mode()[0], inplace = True)
df_test['LBXGLT'].fillna(df_test['LBXGLT'].median(), inplace = True)
df_test['LBXIN'].fillna(df_test['LBXIN'].median(), inplace = True)

In [67]:
df_test.isnull().sum()

RIAGENDR    0
PAQ605      0
BMXBMI      0
LBXGLU      0
DIQ010      0
LBXGLT      0
LBXIN       0
dtype: int64

In [68]:
df_test = pd.get_dummies(df_test, columns=['RIAGENDR'], drop_first=True)
df_test

PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  RIAGENDR_2.0
0       1.0    32.2    96.0     2.0   135.0  15.11             0
1       2.0    26.3   100.0     2.0   141.0  15.26             1
2       2.0    28.6   107.0     2.0   136.0   8.82             0
3       1.0    22.1    93.0     2.0   111.0  12.13             1
4       1.0    24.7    91.0     2.0   105.0   3.12             0
..      ...     ...     ...     ...     ...    ...           ...
307     2.0    21.9    82.0     2.0    82.0   2.54             1
308     1.0    33.3    95.0     2.0    77.0   6.36             1
309     2.0    41.5    91.0     2.0   149.0  15.52             1
310     2.0    22.5    82.0     2.0    93.0   1.39             1
311     2.0    16.1    96.0     2.0   197.0   8.57             0

[312 rows x 7 columns]

In [69]:
count_outliers_iqr(df_test)

Feature  Outlier Count
0        PAQ605             61
1        BMXBMI             13
2        LBXGLU             19
3        DIQ010              8
4        LBXGLT             16
5         LBXIN             21
6  RIAGENDR_2.0              0

In [70]:
columns_to_cap = ['BMXBMI', 'LBXGLU', 'LBXGLT','LBXIN']
df_test = cap_outliers_specific(df_test, columns_to_cap)

In [71]:
df_test[nhanes_columns] = scaler.transform(df_test[nhanes_columns])

In [72]:
y_final = final_model.predict(df_test)
y_final_pred = pd.DataFrame(y_final, columns = ['age_group'])
y_final_pred.to_csv('submission.csv', index = False)